import pygame


BOARD_SIZE = 10
ORIENTATIONS = ['h', 'v']
HORIZONTAL_INDEX = 0
VERTICAL_INDEX = 1
LOWER_COORDINATE_BOUND = 0
UPPER_COORDINATE_BOUND = BOARD_SIZE - 1
LENGTH_OF_COORDINATE = 2
COLUMN_COORDINATE_INDEX = 0
ROW_COORDINATE_INDEX = 1
CHEAT_CODE = 'CHEAT'
SHIPS_NAME_AND_SIZES = {"Carrier": 5, "Battleship": 4, "Cruiser": 3, "Submarine": 3, "Destroyer": 2}
SHIP_SYMBOL = 'S'
HIT_SYMBOL = 'X'
MISS_SYMBOL = 'O'
EMPTY_SYMBOL = ' '

# GUI
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
WHITE = (255, 255, 255)
BUTTON_COLOR = (0, 200, 150)
BUTTON_HOVER_COLOR = (0, 255, 200)
TEXT_COLOR = (0, 0, 0)

TITLE_POSITION_RATIO = 4
PLAY_BUTTON_X_OFFSET = 100
PLAY_BUTTON_Y_OFFSET = 25
PLAY_BUTTON_WIDTH = 200
PLAY_BUTTON_HEIGHT = 50

# ship button layout
SHIP_INITIAL_Y = 50
SHIP_BUTTON_HORIZONTAL_X = 50
SHIP_BUTTON_VERTICAL_X = 210
SHIP_BUTTON_Y_INCREMENT = 40
SHIP_BUTTON_WIDTH = 150
SHIP_BUTTON_HEIGHT = 30

# board layout
BOARD_START_X = 400
BOARD_START_Y = 50
CELL_SIZE = 30

# PYGAME
MOUSE_BUTTON_DOWN = pygame.MOUSEBUTTONDOWN
VIDEO_RESIZE = pygame.VIDEORESIZE

# End
BACKGROUND_COLOR = (0, 0, 0)  
END_TEXT_COLOR = (255, 255, 255) 

SHIP_COLOR = (0, 128, 0)       # green
HIT_COLOR = (255, 0, 0)        # red
MISS_COLOR = (255, 255, 0)     # yellow
EMPTY_COLOR = (200, 200, 200)  # grey
BORDER_WIDTH = 1 

HUMAN_TEXT = "Human Ship"
COMPUTER_TEXT = "Computer Ship"
TEXT_OFFSET = 10