# Appears at the top of the reports
serenity.project.name = Lab 5 Take-Home — Wikipedia Web UI tests (Serenity + JUnit)

webdriver.autodownload = false
webdriver.driver = chrome
webdriver.chrome.driver = src/test/resources/webdriver/mac/chromedriver-mac-arm64/chromedriver
headless.mode = true

# Root package for any JUnit acceptance tests
serenity.test.root = org.example.features

# Customise browser size
serenity.browser.height = 1200
serenity.browser.width = 1600
